# Generated by Django 4.0.dev20210825111435 on 2021-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_avater'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, upload_to='blog/static/content/'),
        ),
    ]
