# Generated by Django 4.0.dev20210825111435 on 2021-09-30 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('finish_time', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='update_time',
            field=models.DateField(),
        ),
    ]
