# Generated by Django 3.2 on 2021-10-13 02:33

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_todo_alter_article_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro',
            field=mdeditor.fields.MDTextField(blank=True, default='GuessWhoAmI!'),
        ),
    ]
